import test from "node:test";
import assert from "node:assert/strict";
import { JobStatus, RetryStrategy, WorkerStatus } from "@prisma/client";
import { prisma } from "../lib/prisma.js";
import { Scheduler, calculateNextRunAt } from "./scheduler.js";

const scheduler = new Scheduler();
type Context = Awaited<ReturnType<typeof createContext>>;

async function createContext() {
  const organization = await prisma.organization.findFirstOrThrow({ where: { name: "Codity Demo Org" } });
  const project = await prisma.project.findFirstOrThrow({ where: { organizationId: organization.id, name: "Scheduler Demo" } });
  const policy = await prisma.retryPolicy.create({ data: { name: `step10-policy-${Date.now()}-${Math.random()}`, strategy: RetryStrategy.FIXED, maxAttempts: 3, initialDelayMs: 100, maxDelayMs: 1000, backoffMultiplier: 1, jitter: false } });
  const queue = await prisma.queue.create({ data: { projectId: project.id, name: `step10-queue-a-${Date.now()}-${Math.random()}`, description: "Step 10 test queue", defaultPriority: 7, concurrencyLimit: 10, isPaused: false, retryPolicyId: policy.id } });
  const queueB = await prisma.queue.create({ data: { projectId: project.id, name: `step10-queue-b-${Date.now()}-${Math.random()}`, description: "Step 10 test queue", defaultPriority: 2, concurrencyLimit: 10, isPaused: false, retryPolicyId: policy.id } });
  const worker = await prisma.worker.create({ data: { organizationId: organization.id, name: `step10-worker-${Date.now()}-${Math.random()}`, status: WorkerStatus.ONLINE, concurrency: 1, currentJobCount: 0 } });
  return { organization, project, policy, queue, queueB, worker };
}

async function cleanup(value: Context) {
  const queueIds = [value.queue.id, value.queueB.id];
  await prisma.jobLog.deleteMany({ where: { execution: { job: { queueId: { in: queueIds } } } } });
  await prisma.jobExecution.deleteMany({ where: { job: { queueId: { in: queueIds } } } });
  await prisma.job.deleteMany({ where: { queueId: { in: queueIds } } });
  await prisma.scheduledJob.deleteMany({ where: { queueId: { in: queueIds } } });
  await prisma.worker.deleteMany({ where: { id: value.worker.id } });
  await prisma.queue.deleteMany({ where: { id: { in: queueIds } } });
  await prisma.retryPolicy.deleteMany({ where: { id: value.policy.id } });
}

async function createDefinition(value: Context, queueId = value.queue.id, nextRunAt = new Date("2020-01-01T00:00:00.000Z"), enabled = true) {
  return scheduler.createScheduledJob({ queueId, jobType: "step10-recurring", payload: { step: 10 }, cronExpression: "* * * * *", nextRunAt, enabled });
}

async function createScheduledJob(value: Context, queueId: string, status: JobStatus, scheduledAt: Date) {
  return prisma.job.create({ data: { queueId, jobType: "step10-delayed", payload: { delayed: true }, status, priority: 9, scheduledAt, maxAttempts: 3, attemptCount: 0, idempotencyKey: `${Date.now()}-${Math.random()}` } });
}

test("past scheduled jobs become QUEUED and future jobs remain SCHEDULED", async () => { const value = await createContext(); const past = await createScheduledJob(value, value.queue.id, JobStatus.SCHEDULED, new Date("2020-01-01T00:00:00Z")); const future = await createScheduledJob(value, value.queue.id, JobStatus.SCHEDULED, new Date("2099-01-01T00:00:00Z")); try { const result = await scheduler.promoteDueScheduledJobs(value.queue.id); const rows = await prisma.job.findMany({ where: { id: { in: [past.id, future.id] } } }); assert.deepEqual(result.promotedJobIds, [past.id]); assert.equal(rows.find((row) => row.id === past.id)?.status, JobStatus.QUEUED); assert.equal(rows.find((row) => row.id === future.id)?.status, JobStatus.SCHEDULED); assert.equal(rows.find((row) => row.id === past.id)?.attemptCount, 0); assert.equal(await prisma.jobExecution.count({ where: { jobId: past.id } }), 0); } finally { await cleanup(value); } });

test("scheduled promotion is queue-scoped and does not involve workers", async () => { const value = await createContext(); const a = await createScheduledJob(value, value.queue.id, JobStatus.SCHEDULED, new Date("2020-01-01T00:00:00Z")); const b = await createScheduledJob(value, value.queueB.id, JobStatus.SCHEDULED, new Date("2020-01-01T00:00:00Z")); const beforeWorker = await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }); try { await scheduler.promoteDueScheduledJobs(value.queue.id); assert.equal((await prisma.job.findUniqueOrThrow({ where: { id: a.id } })).status, JobStatus.QUEUED); assert.equal((await prisma.job.findUniqueOrThrow({ where: { id: b.id } })).status, JobStatus.SCHEDULED); assert.deepEqual(await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }), beforeWorker); } finally { await cleanup(value); } });

test("recurring materialization creates a scheduled concrete job and advances nextRunAt", async () => { const value = await createContext(); const definition = await createDefinition(value); try { const result = await scheduler.materializeDueScheduledJob(definition.id, value.queue.id); assert.equal(result.materialized, true); const generated = result.job!; assert.equal(generated.status, JobStatus.SCHEDULED); assert.equal(generated.scheduledAt.toISOString(), definition.nextRunAt.toISOString()); assert.equal(generated.attemptCount, 0); assert.equal(generated.queueId, value.queue.id); assert.equal(generated.priority, 7); assert.equal(generated.claimedBy, null); assert.equal(await prisma.jobExecution.count({ where: { jobId: generated.id } }), 0); assert.equal(result.scheduledJob?.enabled, true); assert.ok(result.scheduledJob!.nextRunAt > new Date()); } finally { await cleanup(value); } });

test("generated scheduled jobs can use the frozen SCHEDULED to QUEUED transition", async () => { const value = await createContext(); const definition = await createDefinition(value, value.queue.id, new Date("2020-01-01T00:00:00Z")); try { const result = await scheduler.materializeDueScheduledJob(definition.id); assert.ok(result.job); await scheduler.promoteDueScheduledJobs(value.queue.id); assert.equal((await prisma.job.findUniqueOrThrow({ where: { id: result.job!.id } })).status, JobStatus.QUEUED); } finally { await cleanup(value); } });

test("disabled and future definitions do nothing", async () => { const value = await createContext(); const disabled = await createDefinition(value, value.queue.id, new Date("2020-01-01T00:00:00Z"), false); const future = await createDefinition(value, value.queue.id, new Date("2099-01-01T00:00:00Z")); try { const disabledResult = await scheduler.materializeDueScheduledJob(disabled.id); const futureResult = await scheduler.materializeDueScheduledJob(future.id); assert.equal(disabledResult.materialized, false); assert.equal(futureResult.materialized, false); assert.equal(await prisma.job.count({ where: { queueId: value.queue.id } }), 0); assert.equal((await prisma.scheduledJob.findUniqueOrThrow({ where: { id: disabled.id } })).enabled, false); assert.equal((await prisma.scheduledJob.findUniqueOrThrow({ where: { id: future.id } })).nextRunAt.toISOString(), "2099-01-01T00:00:00.000Z"); } finally { await cleanup(value); } });

test("invalid cron expressions are rejected before definition creation", async () => { const value = await createContext(); try { await assert.rejects(() => scheduler.createScheduledJob({ queueId: value.queue.id, jobType: "invalid", payload: {}, cronExpression: "not a cron", nextRunAt: new Date("2027-01-01T00:00:00Z") }), /Invalid cron expression/); assert.equal(await prisma.scheduledJob.count({ where: { queueId: value.queue.id } }), 0); } finally { await cleanup(value); } });

test("next run calculation is strict and uses the cron parser", () => { const next = calculateNextRunAt("*/5 * * * *", new Date("2027-01-01T00:00:00Z")); assert.equal(next.toISOString(), "2027-01-01T00:05:00.000Z"); });

test("repeated materialization is idempotent per occurrence", async () => { const value = await createContext(); const definition = await createDefinition(value); try { const first = await scheduler.materializeDueScheduledJob(definition.id); const second = await scheduler.materializeDueScheduledJob(definition.id); assert.equal(first.materialized, true); assert.equal(second.materialized, false); assert.equal(await prisma.job.count({ where: { queueId: value.queue.id } }), 1); } finally { await cleanup(value); } });

test("ten concurrent schedulers materialize exactly one current occurrence", async () => { const value = await createContext(); const definition = await createDefinition(value); try { const results = await Promise.all(Array.from({ length: 10 }, () => scheduler.materializeDueScheduledJob(definition.id, value.queue.id))); const wins = results.filter((result) => result.materialized); const jobs = await prisma.job.findMany({ where: { queueId: value.queue.id } }); const persisted = await prisma.scheduledJob.findUniqueOrThrow({ where: { id: definition.id } }); assert.equal(wins.length, 1); assert.equal(jobs.length, 1); assert.equal(new Set(jobs.map((job) => job.id)).size, 1); assert.ok(persisted.nextRunAt > new Date()); assert.equal(persisted.enabled, true); assert.equal(jobs[0]!.status, JobStatus.SCHEDULED); assert.equal(jobs[0]!.attemptCount, 0); assert.equal(jobs[0]!.claimedBy, null); } finally { await cleanup(value); } });

test("materialization rollback leaves no partial job or definition update", async () => { const value = await createContext(); const definition = await createDefinition(value); const failing = new Scheduler({ beforeDefinitionUpdate: () => { throw new Error("controlled scheduler failure"); } }); try { await assert.rejects(() => failing.materializeDueScheduledJob(definition.id), /controlled scheduler failure/); assert.equal(await prisma.job.count({ where: { queueId: value.queue.id } }), 0); assert.equal((await prisma.scheduledJob.findUniqueOrThrow({ where: { id: definition.id } })).nextRunAt.toISOString(), definition.nextRunAt.toISOString()); } finally { await cleanup(value); } });

test("multiple occurrences advance one cron occurrence at a time without executions", async () => { const value = await createContext(); const definition = await createDefinition(value, value.queue.id, new Date("2020-01-01T00:00:00Z")); try { const first = await scheduler.materializeDueScheduledJob(definition.id); await prisma.scheduledJob.update({ where: { id: definition.id }, data: { nextRunAt: new Date("2020-01-01T00:01:00Z") } }); const second = await scheduler.materializeDueScheduledJob(definition.id); const jobs = await prisma.job.findMany({ where: { queueId: value.queue.id }, orderBy: { scheduledAt: "asc" } }); assert.equal(first.materialized, true); assert.equal(second.materialized, true); assert.deepEqual(jobs.map((job) => job.scheduledAt.toISOString()), ["2020-01-01T00:00:00.000Z", "2020-01-01T00:01:00.000Z"]); assert.equal(await prisma.jobExecution.count({ where: { jobId: { in: jobs.map((job) => job.id) } } }), 0); } finally { await cleanup(value); } });

test("tenant and queue ownership remain unchanged during materialization", async () => { const value = await createContext(); const definition = await createDefinition(value, value.queue.id); const queueBefore = await prisma.queue.findUniqueOrThrow({ where: { id: value.queue.id }, select: { id: true, projectId: true, project: { select: { organizationId: true } } } }); try { const result = await scheduler.materializeDueScheduledJob(definition.id, value.queue.id); const queueAfter = await prisma.queue.findUniqueOrThrow({ where: { id: value.queue.id }, select: { id: true, projectId: true, project: { select: { organizationId: true } } } }); assert.equal(result.job?.queueId, queueBefore.id); assert.equal(queueAfter.projectId, queueBefore.projectId); assert.equal(queueAfter.project.organizationId, queueBefore.project.organizationId); } finally { await cleanup(value); } });

test("scheduler does not invoke workers or claim scheduled jobs", async () => { const value = await createContext(); const definition = await createDefinition(value); const beforeWorker = await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }); try { const result = await scheduler.materializeDueScheduledJob(definition.id, value.queue.id); const generated = await prisma.job.findUniqueOrThrow({ where: { id: result.job!.id } }); const afterWorker = await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }); assert.equal(result.materialized, true); assert.deepEqual(afterWorker, beforeWorker); assert.equal(generated.status, JobStatus.SCHEDULED); assert.equal(generated.claimedBy, null); assert.equal(generated.claimedAt, null); assert.equal(generated.attemptCount, 0); assert.equal(await prisma.jobExecution.count({ where: { jobId: generated.id } }), 0); } finally { await cleanup(value); } });

test("scheduler does not perform retry transitions", async () => { const value = await createContext(); const failed = await prisma.job.create({ data: { queueId: value.queue.id, jobType: "step10-failed-control", payload: {}, status: JobStatus.FAILED, priority: 1, scheduledAt: new Date(), maxAttempts: 3, attemptCount: 1, idempotencyKey: `${Date.now()}-${Math.random()}` } }); const retry = await prisma.job.create({ data: { queueId: value.queue.id, jobType: "step10-retry-control", payload: {}, status: JobStatus.RETRY, priority: 1, scheduledAt: new Date("2099-01-01T00:00:00Z"), maxAttempts: 3, attemptCount: 1, idempotencyKey: `${Date.now()}-${Math.random()}` } }); try { await scheduler.promoteDueScheduledJobs(value.queue.id); const failedAfter = await prisma.job.findUniqueOrThrow({ where: { id: failed.id } }); const retryAfter = await prisma.job.findUniqueOrThrow({ where: { id: retry.id } }); assert.equal(failedAfter.status, JobStatus.FAILED); assert.equal(retryAfter.status, JobStatus.RETRY); assert.equal(await prisma.jobExecution.count({ where: { jobId: { in: [failed.id, retry.id] } } }), 0); } finally { await cleanup(value); } });

test("scheduler does not perform dead-letter transitions", async () => { const value = await createContext(); const failed = await prisma.job.create({ data: { queueId: value.queue.id, jobType: "step10-dlq-control", payload: {}, status: JobStatus.FAILED, priority: 1, scheduledAt: new Date(), maxAttempts: 1, attemptCount: 1, idempotencyKey: `${Date.now()}-${Math.random()}` } }); try { await scheduler.promoteDueScheduledJobs(value.queue.id); const persisted = await prisma.job.findUniqueOrThrow({ where: { id: failed.id } }); assert.equal(persisted.status, JobStatus.FAILED); assert.equal(await prisma.deadLetterEntry.count({ where: { jobId: failed.id } }), 0); assert.equal(await prisma.jobExecution.count({ where: { jobId: failed.id } }), 0); } finally { await cleanup(value); } });

test("scheduler does not perform heartbeat or stale-worker recovery", async () => { const value = await createContext(); const definition = await createDefinition(value); await prisma.$executeRaw`UPDATE "Worker" SET "lastHeartbeatAt" = CURRENT_TIMESTAMP - INTERVAL '1 minute', "currentJobCount" = 4 WHERE "id" = ${value.worker.id}::uuid`; const beforeWorker = await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }); const beforeHeartbeats = await prisma.workerHeartbeat.count({ where: { workerId: value.worker.id } }); try { await scheduler.materializeDueScheduledJob(definition.id, value.queue.id); const afterWorker = await prisma.worker.findUniqueOrThrow({ where: { id: value.worker.id } }); const afterHeartbeats = await prisma.workerHeartbeat.count({ where: { workerId: value.worker.id } }); assert.deepEqual(afterWorker, beforeWorker); assert.equal(afterHeartbeats, beforeHeartbeats); assert.equal(afterWorker.status, WorkerStatus.ONLINE); assert.equal(afterWorker.currentJobCount, 4); } finally { await cleanup(value); } });

test("paused queues block promotion and recurring materialization", async () => { const value = await createContext(); const definition = await createDefinition(value); const delayed = await createScheduledJob(value, value.queue.id, JobStatus.SCHEDULED, new Date("2020-01-01T00:00:00Z")); await prisma.queue.update({ where: { id: value.queue.id }, data: { isPaused: true } }); try { const beforeDefinition = await prisma.scheduledJob.findUniqueOrThrow({ where: { id: definition.id } }); const promotion = await scheduler.promoteDueScheduledJobs(value.queue.id); const materialization = await scheduler.materializeDueScheduledJob(definition.id, value.queue.id); const afterDefinition = await prisma.scheduledJob.findUniqueOrThrow({ where: { id: definition.id } }); assert.deepEqual(promotion.promotedJobIds, []); assert.equal((await prisma.job.findUniqueOrThrow({ where: { id: delayed.id } })).status, JobStatus.SCHEDULED); assert.equal(materialization.materialized, false); assert.equal(afterDefinition.nextRunAt.toISOString(), beforeDefinition.nextRunAt.toISOString()); assert.equal(await prisma.job.count({ where: { queueId: value.queue.id } }), 1); } finally { await cleanup(value); } });
