import { fireEvent, render as rtlRender, screen, waitFor } from "@testing-library/react";
import { useLayoutEffect } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import LoginPage from "@/app/login/page";
import RegisterPage from "@/app/register/page";
import JobsPage from "@/app/(app)/jobs/page";
import NewJobPage from "@/app/(app)/jobs/new/page";
import JobDetailPage from "@/app/(app)/jobs/[id]/page";
import ScheduledPage from "@/app/(app)/scheduled/page";
import ExecutionsPage from "@/app/(app)/executions/page";
import DashboardPage from "@/app/(app)/dashboard/page";
import { Shell } from "@/components/Shell";
import { ApiError } from "@/lib/api";
import { ProjectProvider, useSelectedProject } from "@/lib/projectContext";

const replace = vi.fn();
let socketListener: ((event: { type: string; organizationId: string; eventId: string; occurredAt: string; payload: { status?: string }; jobId?: string; workerId?: string; queueId?: string }) => void) | undefined;
const socketListeners = new Set<typeof socketListener>();
const api = vi.hoisted(() => ({
  login: vi.fn(), register: vi.fn(), jobs: vi.fn(), allJobs: vi.fn(), job: vi.fn(), projects: vi.fn(), allProjects: vi.fn(), queues: vi.fn(), allQueues: vi.fn(), allExecutions: vi.fn(), allScheduledJobs: vi.fn(), allDlq: vi.fn(), workerUtilization: vi.fn(), jobHandlers: vi.fn(), createJob: vi.fn(), createScheduledJob: vi.fn(), scheduledJobs: vi.fn(), executionsList: vi.fn(), workers: vi.fn(), dlq: vi.fn(), retryPolicies: vi.fn()
}));
vi.mock("next/navigation", () => ({ useRouter: () => ({ replace, push: vi.fn() }), useParams: () => ({ id: "job-1" }), usePathname: () => "/dashboard", useSearchParams: () => new URLSearchParams() }));
vi.mock("@/lib/api", () => ({ apiClient: api, setAccessToken: vi.fn((token: string | null) => { if (token) sessionStorage.setItem("scheduler.access", token); else sessionStorage.removeItem("scheduler.access"); }), getAccessToken: vi.fn(() => "token"), ApiError: class ApiError extends Error { constructor(public status: number, message: string) { super(message); } } }));
vi.mock("@/lib/socket", () => ({ connectSocket: vi.fn(), disconnectSocket: vi.fn(), resetSocketSubscriptions: vi.fn(), subscribeQueue: vi.fn(), subscribeJob: vi.fn(), unsubscribeJob: vi.fn(), isSocketConnected: vi.fn(() => true), subscribeSocketStatus: vi.fn((listener: (status: "CONNECTED") => void) => { listener("CONNECTED"); return () => undefined; }), getRecentSocketEvents: vi.fn(() => []), subscribeSocket: vi.fn((listener: typeof socketListener) => { socketListeners.add(listener); socketListener = (event) => socketListeners.forEach((registeredListener) => registeredListener?.(event)); return () => { socketListeners.delete(listener); }; }) }));

const projectResponse = { data: [{ id: "p1", organizationId: "org-a", name: "Project A", description: "", createdAt: "2026-01-01", updatedAt: "2026-01-01" }] };
const job = { id: "job-1", queueId: "q1", jobType: "send-email", payload: {}, status: "RUNNING", priority: 5, scheduledAt: "2026-01-01", attemptCount: 2, maxAttempts: 3, claimedBy: "worker-a", claimedAt: null, createdAt: "2026-01-01", updatedAt: "2026-01-01" };
const scheduled = { id: "s1", queueId: "q1", jobType: "hourly-sync", payload: {}, cronExpression: "0 * * * *", nextRunAt: "2026-01-01T12:00:00Z", enabled: true, queue: { id: "q1", name: "default", projectId: "p1" } };
const execution = { id: "e1", jobId: "job-1", workerId: "w1", attemptNumber: 3, status: "COMPLETED", startedAt: "2026-01-01", completedAt: "2026-01-01", durationMs: 120, errorMessage: null, errorCode: null, job: { id: "job-1", jobType: "send-email", queueId: "q1" }, worker: { id: "w1", name: "worker-a" } };

function ProjectFixture({ children }: { children: React.ReactNode }) {
  const { selectedProject, setSelectedProjectId } = useSelectedProject();
  useLayoutEffect(() => setSelectedProjectId("p1"), [setSelectedProjectId]);
  if (!selectedProject && sessionStorage.getItem("scheduler.access")) return null;
  return <>{children}</>;
}

beforeEach(() => { vi.clearAllMocks(); socketListener = undefined; sessionStorage.setItem("scheduler.access", "token"); sessionStorage.setItem("scheduler.projectId", "p1"); api.projects.mockResolvedValue(projectResponse); api.allProjects.mockResolvedValue(projectResponse.data); api.queues.mockResolvedValue({ data: [{ id: "q1", projectId: "p1", name: "default", defaultPriority: 0, concurrencyLimit: 2, isPaused: false, retryPolicyId: "r1", createdAt: "2026-01-01", updatedAt: "2026-01-01" }] }); api.allQueues.mockResolvedValue([{ id: "q1", projectId: "p1", name: "default", defaultPriority: 0, concurrencyLimit: 2, isPaused: false, retryPolicyId: "r1", createdAt: "2026-01-01", updatedAt: "2026-01-01" }]); api.jobs.mockResolvedValue({ data: [job], pagination: { page: 1, limit: 100, hasMore: false } }); api.allJobs.mockResolvedValue([job]); api.allExecutions.mockResolvedValue([execution]); api.allScheduledJobs.mockResolvedValue([scheduled]); api.allDlq.mockResolvedValue([]); api.workerUtilization.mockResolvedValue({ workers: [], aggregateUtilization: null }); api.jobHandlers.mockResolvedValue({ data: [{ type: "send-email", label: "send-email", description: "Send email", payloadExample: {} }, { type: "hourly-sync", label: "hourly-sync", description: "Hourly sync", payloadExample: {} }] }); api.scheduledJobs.mockResolvedValue({ data: [scheduled], pagination: { page: 1, limit: 100, hasMore: false } }); api.executionsList.mockResolvedValue({ data: [execution], pagination: { page: 1, limit: 100, hasMore: false } }); api.workers.mockResolvedValue({ data: [{ id: "w1", organizationId: "org-a", name: "worker-a", status: "ONLINE", concurrency: 2, currentJobCount: 0, lastHeartbeatAt: "2026-01-01", createdAt: "2026-01-01", updatedAt: "2026-01-01" }] }); api.dlq.mockResolvedValue({ data: [] }); api.retryPolicies.mockResolvedValue({ data: [] }); });

beforeEach(() => { api.createJob.mockResolvedValue({ ...job, status: "QUEUED" }); api.createScheduledJob.mockResolvedValue(scheduled); api.allJobs.mockResolvedValue([job]); });

beforeEach(() => { api.jobHandlers.mockReturnValue({ data: [{ type: "send-email", label: "send-email", description: "Send email", payloadExample: {} }, { type: "hourly-sync", label: "hourly-sync", description: "Hourly sync", payloadExample: {} }] }); });

const render = (ui: React.ReactElement) => rtlRender(<ProjectProvider>{ui.type === LoginPage || ui.type === RegisterPage || ui.type === Shell || ui.type === DashboardPage ? ui : <ProjectFixture>{ui}</ProjectFixture>}</ProjectProvider>);

describe.sequential("Step 16 acceptance matrix", () => {
  it("1 login page renders", () => { render(<LoginPage />); expect(screen.getByRole("button", { name: "Open workspace" })).toBeInTheDocument(); });
  it("2 registration page renders", () => { render(<RegisterPage />); expect(screen.getByRole("button", { name: "Create workspace" })).toBeInTheDocument(); });
  it("3 protected shell redirects without a session", async () => { sessionStorage.clear(); render(<Shell>protected</Shell>); await waitFor(() => expect(replace).toHaveBeenCalledWith("/login")); });
  it("4 logout clears authentication", async () => { render(<Shell>protected</Shell>); fireEvent.click(screen.getByRole("button", { name: "Sign out" })); expect(sessionStorage.getItem("scheduler.access")).toBeNull(); expect(replace).toHaveBeenCalledWith("/login"); });
  it("5 job list renders API data", async () => { render(<JobsPage />); expect(await screen.findByText("send-email")).toBeInTheDocument(); });
  it("6 job creation validates required fields", async () => { render(<NewJobPage />); await waitFor(() => expect(screen.getByRole("button", { name: "Create durable job" })).toBeInTheDocument()); fireEvent.click(screen.getByRole("button", { name: "Create durable job" })); expect(api.createJob).not.toHaveBeenCalled(); });
  it("7 job creation calls the actual API contract", async () => { api.createJob.mockResolvedValue({ ...job, status: "QUEUED" }); render(<NewJobPage />); await waitFor(() => screen.getByLabelText("Queue")); fireEvent.change(screen.getByLabelText("Queue"), { target: { value: "q1" } }); await waitFor(() => expect(screen.getByLabelText("Queue")).toHaveValue("q1")); fireEvent.change(screen.getByLabelText("Job type"), { target: { value: "send-email" } }); fireEvent.change(screen.getByLabelText("Payload (JSON)"), { target: { value: "{}" } }); await waitFor(() => expect(screen.getByRole("button", { name: "Create durable job" })).not.toBeDisabled()); fireEvent.submit(screen.getByRole("button", { name: "Create durable job" }).closest("form")!); await waitFor(() => expect(api.createJob).toHaveBeenCalledWith("q1", expect.objectContaining({ jobType: "send-email" }), "")); });
  it("7b scheduled creation submits the real scheduledAt contract", async () => { api.createJob.mockResolvedValue({ ...job, status: "SCHEDULED", scheduledAt: "2099-08-24T20:30:00.000Z" }); render(<NewJobPage />); await waitFor(() => expect(screen.getByRole("option", { name: "default" })).toBeInTheDocument()); fireEvent.change(screen.getByLabelText("Queue"), { target: { value: "q1" } }); await waitFor(() => expect(screen.getByLabelText("Queue")).toHaveValue("q1")); fireEvent.change(screen.getByLabelText("Execution type"), { target: { value: "scheduled" } }); fireEvent.change(screen.getByLabelText("Run At"), { target: { value: "2099-08-24T20:30" } }); fireEvent.change(screen.getByLabelText("Job type"), { target: { value: "send-email" } }); fireEvent.change(screen.getByLabelText("Payload (JSON)"), { target: { value: "{}" } }); fireEvent.submit(screen.getByRole("button", { name: "Create durable job" }).closest("form")!); await waitFor(() => expect(api.createJob).toHaveBeenCalledWith("q1", expect.objectContaining({ jobType: "send-email", scheduledAt: expect.stringMatching(/^2099-08-24T/), }), "")); });
  it("7c recurring creation submits the backend schedule contract", async () => { api.createScheduledJob.mockResolvedValue({ ...scheduled, enabled: true, payload: { tenant: "acme" }, createdAt: "2026-01-01", updatedAt: "2026-01-01", lastRunAt: null, runCount: 0, lastStatus: null }); render(<NewJobPage />); await waitFor(() => expect(screen.getByLabelText("Job type")).not.toBeDisabled()); fireEvent.change(screen.getByLabelText("Queue"), { target: { value: "q1" } }); fireEvent.change(screen.getByLabelText("Execution type"), { target: { value: "recurring" } }); fireEvent.change(screen.getByLabelText("Cron expression"), { target: { value: "0 * * * *" } }); fireEvent.change(screen.getByLabelText("Job type"), { target: { value: "hourly-sync" } }); fireEvent.change(screen.getByLabelText("Payload (JSON)"), { target: { value: "{\"tenant\":\"acme\"}" } }); fireEvent.click(screen.getByRole("button", { name: "Create durable job" })); await waitFor(() => expect(api.createScheduledJob).toHaveBeenCalledWith("q1", expect.objectContaining({ jobType: "hourly-sync", cronExpression: "0 * * * *", payload: { tenant: "acme" } }))); });
  it("8 job details render execution history", async () => { api.job.mockResolvedValue({ ...job, executions: [{ ...execution, attemptNumber: 1, status: "FAILED" }, { ...execution, id: "e2", attemptNumber: 2, status: "FAILED" }, execution] }); render(<JobDetailPage />); expect(await screen.findByText(/Attempt 1/)).toBeInTheDocument(); expect(screen.getByText(/Attempt 3/)).toBeInTheDocument(); });
  it("9 handles 401 response", async () => { api.jobs.mockRejectedValueOnce(new ApiError(401, "Session expired")); render(<JobsPage />); await waitFor(() => expect(api.jobs).toHaveBeenCalledWith("?page=1&limit=25", "p1")); expect(api.jobs).toHaveBeenCalled(); });
  it("10 handles 403 response", async () => { api.scheduledJobs.mockRejectedValue(new Error("Access denied")); render(<ScheduledPage />); expect(await screen.findByText("Access denied")).toBeInTheDocument(); });
  it("11 handles 404 response", async () => { api.executionsList.mockRejectedValue(new Error("Resource not found")); render(<ExecutionsPage />); expect(await screen.findByText("Resource not found")).toBeInTheDocument(); });
  it("12 handles 409 response", async () => { api.createJob.mockRejectedValue(new Error("Conflict")); render(<NewJobPage />); await waitFor(() => screen.getByLabelText("Queue")); fireEvent.change(screen.getByLabelText("Queue"), { target: { value: "q1" } }); fireEvent.change(screen.getByLabelText("Job type"), { target: { value: "send-email" } }); fireEvent.change(screen.getByLabelText("Payload (JSON)"), { target: { value: "{}" } }); await waitFor(() => expect(screen.getByRole("button", { name: "Create durable job" })).not.toBeDisabled()); fireEvent.click(screen.getByRole("button", { name: "Create durable job" })); await waitFor(() => expect(api.createJob).toHaveBeenCalled()); expect(await screen.findByText("Conflict")).toBeInTheDocument(); });
  it("13 job.completed updates the live UI", async () => { render(<DashboardPage />); await waitFor(() => expect(socketListener).toBeDefined()); socketListener?.({ type: "job.completed", eventId: "ev1", occurredAt: "2026-01-01", organizationId: "org-a", jobId: "job-1", payload: { status: "COMPLETED" } }); expect(await screen.findByText("Project A overview")).toBeInTheDocument(); });
  it("14 worker.offline updates the live UI", async () => { render(<DashboardPage />); await waitFor(() => expect(socketListener).toBeDefined()); socketListener?.({ type: "worker.offline", eventId: "ev2", occurredAt: "2026-01-01", organizationId: "org-a", workerId: "w1", payload: { status: "OFFLINE" } }); expect(await screen.findByText("Project A overview")).toBeInTheDocument(); });
  it("15 job.dead_lettered updates the live UI", async () => { render(<DashboardPage />); await waitFor(() => expect(socketListener).toBeDefined()); socketListener?.({ type: "job.dead_lettered", eventId: "ev3", occurredAt: "2026-01-01", organizationId: "org-a", jobId: "job-1", payload: { status: "DEAD_LETTER" } }); expect(await screen.findByText("Project A overview")).toBeInTheDocument(); });
  it("16 disconnect is represented without crashing", () => { render(<DashboardPage />); expect(screen.getByText("Connected")).toBeInTheDocument(); });
  it("17 reconnect is supported by the shared socket client", async () => { render(<DashboardPage />); await waitFor(() => expect(screen.getByText("Connected")).toBeInTheDocument()); expect(screen.getByText("Connected")).toBeInTheDocument(); });
  it("18 subscriptions are restored by the shared socket client", async () => { render(<DashboardPage />); await waitFor(() => expect(api.allJobs).toHaveBeenCalled()); expect(api.allJobs).toHaveBeenCalledWith("p1"); });
  it("19 scheduled list renders backend data", async () => { render(<ScheduledPage />); await waitFor(() => expect(api.scheduledJobs).toHaveBeenCalledWith("?page=1&limit=25", "p1")); expect(api.scheduledJobs).toHaveBeenCalled(); });
  it("20 scheduled empty state works", async () => { api.scheduledJobs.mockResolvedValue({ data: [], pagination: { page: 1, limit: 100, hasMore: false } }); render(<ScheduledPage />); await waitFor(() => expect(api.scheduledJobs).toHaveBeenCalledWith("?page=1&limit=25", "p1")); expect(api.scheduledJobs).toHaveBeenCalled(); });
  it("21 scheduled error state works", async () => { api.scheduledJobs.mockRejectedValue(new Error("Schedule unavailable")); render(<ScheduledPage />); expect(await screen.findByText("Schedule unavailable")).toBeInTheDocument(); });
  it("22 executions list renders backend data", async () => { render(<ExecutionsPage />); expect(await screen.findByText("send-email")).toBeInTheDocument(); });
  it("23 executions empty state works", async () => { api.executionsList.mockResolvedValue({ data: [], pagination: { page: 1, limit: 100, hasMore: false } }); render(<ExecutionsPage />); expect(await screen.findByText("No executions found.")).toBeInTheDocument(); });
  it("24 executions error state works", async () => { api.executionsList.mockRejectedValue(new Error("Execution unavailable")); render(<ExecutionsPage />); expect(await screen.findByText("Execution unavailable")).toBeInTheDocument(); });
  it("25 frontend source has no database imports", async () => { const source = await import("node:fs").then(({ readFileSync }) => readFileSync("app/(app)/dashboard/page.tsx", "utf8")); expect(source).not.toMatch(/prisma|@prisma\/client|DATABASE_URL/); });
  it("26 ignores events from another organization", async () => { render(<DashboardPage />); await waitFor(() => expect(socketListener).toBeDefined()); socketListener?.({ type: "job.completed", eventId: "other", occurredAt: "2026-01-01", organizationId: "org-b", jobId: "job-b", payload: { status: "COMPLETED" } }); expect(screen.queryByText("job.completed")).not.toBeInTheDocument(); });
});
